# Generated by Django 5.0.1 on 2024-01-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_admin',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('login_name', models.CharField(max_length=50)),
                ('login_email', models.EmailField(max_length=254)),
                ('login_pass', models.CharField(max_length=50)),
            ],
        ),
    ]
